apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-retry-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512MiB
  storageClassName: netapp-file-standard