env:
  - name: NODE_ENV
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: NODE_ENV
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: DB_HOST
  - name: DB_PORT
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: DB_PORT
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
          name: postgresql
          key: database-name
  - name: DB_SCHEMA
    valueFrom:
      secretKeyRef:
          name: postgresql
          key: database-schema
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
          name: postgresql
          key: database-user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
          name: postgresql
          key: database-password
  - name: DB_SYNCHRONIZE
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: DB_SYNCHRONIZE
  - name: DB_RUN_MIGRATIONS
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: DB_RUN_MIGRATIONS
  - name: DB_LOGGING
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: DB_LOGGING
  - name: REDIS_HOST
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: REDIS_HOST
  - name: REDIS_PORT
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: REDIS_PORT
  - name: REDIS_USER
    valueFrom:
      secretKeyRef:
          name: redis
          key: database-username
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
          name: redis
          key: database-password
  - name: SIEBEL_RETRY_DELAY_MS
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: SIEBEL_RETRY_DELAY_MS
  - name: SIEBEL_BACKOFF_DELAY_MS
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: SIEBEL_BACKOFF_DELAY_MS
  - name: SIEBEL_ACCESS_TOKEN_URL
    valueFrom:
      configMapKeyRef:
          name: social-retry-config
          key: SIEBEL_ACCESS_TOKEN_URL
  - name: SIEBEL_CLIENT_ID
    valueFrom:
      secretKeyRef:
          name: social-retry
          key: SIEBEL_CLIENT_ID
  - name: SIEBEL_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
          name: social-retry
          key: SIEBEL_CLIENT_SECRET