replicaCount: 1
 
image:
  repository: ghcr.io/bcgov/social-retry
  tag: '<set by CI/CD>'
  pullPolicy: Always
 
service:
  type: ClusterIP
  port: 443
  containerPort: 3000
 
resources: {}
 
nodeSelector: {}
 
tolerations: []
 
affinity: {}

socialRetryAppEnv: '<set by CI/CD>'

aps:
  namespace: '<set by CI/CD>'

socialRetryAppBuildLabel:
  version: '<set by CI/CD>'

patroni:
  resources:
    limits:
      cpu: 75m
      memory: 300Mi
    requests:
      cpu: 20m
      memory: 256Mi

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  annotations: {}
  mountPath: "/home/postgres/pgdata"
  size: 300MiB
  storageClass: "netapp-block-standard"
