name: Deploy Redis
permissions:
  contents: read
  deployments: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - test
          - main

env:
  HELM_RELEASE_NAME: redis-retry-deployment

jobs:     
  deploy:
      environment: ${{ github.event.inputs.environment }}
      runs-on: ubuntu-24.04

      steps:
        - name: Checkout the repository
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

        - name: Install CLI tools from OpenShift Mirror
          uses: redhat-actions/openshift-tools-installer@37eb3cfb20ac2df6f0511ffa71cd917e4d49cabf #v3.1.0
          with:
            oc: "latest"
            helm: "latest"

        - name: Authenticate with OpenShift
          uses: redhat-actions/oc-login@2a1614bc977c054c8786c8e35fc9534bd0ddc156 #v2.0.1
          with:
            openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
            namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
            openshift_token: ${{ secrets.OPENSHIFT_SERVICE_ACCOUNT_TOKEN }}
            insecure_skip_tls_verify: true

        - name: Deploy with Helm
          run: |
            helm upgrade -f redis/values.yaml \
              --install ${{ env.HELM_RELEASE_NAME }} ./redis \
              --namespace ${{ secrets.OPENSHIFT_NAMESPACE }}